Added BMS Tutorial Notebook
AutoResearch/autora-theorist-bms pull request #39
Opened 2023-08-30 18:44 UTC by TheLemonPig

The full notebook is added under the name "Tutorial". I figured it would help to keep the simple use case created by Ben, for those less familiar with coding.

2023-08-31 12:08 UTC, benwandrew reviewed
awesome, thanks! my only two cents are the following:
1. shall we title this something more descriptive than "Tutorial"?
2. can we include one or two sentences at the very top of the notebook which give some context / lay out the objective(s) of the notebook? eg, "in this tutorial, we will walk through how to [abc], [xyz]... we begin by..."

2023-08-31 17:14 UTC, TheLemonPig commented
> awesome, thanks! my only two cents are the following:
> 
> 1. shall we title this something more descriptive than "Tutorial"?
> 2. can we include one or two sentences at the very top of the notebook which give some context / lay out the objective(s) of the notebook? eg, "in this tutorial, we will walk through how to [abc], [xyz]... we begin by..."

Good points. I'll create some suggested changes and see what you think about them before committing

2023-09-03 10:26 UTC, musslick requested changes
Looks great! The only item is that I would change the title to "Automated Scientific Discovery with the Bayesian Machine Scientist".

2023-09-05 18:26 UTC, TheLemonPig commented on mkdocs.yml
> +    - Tutorial: 'Tutorial.ipynb'
```suggestion
    - Tutorial: 'Automated Scientific Discovery with the Bayesian Machine Scientist.ipynb'
```

2023-09-07 20:20 UTC, benwandrew approved these changes
terrific, thanks for the updates!

2023-09-15 14:46 UTC, TheLemonPig commented
@benwandrew we should close this PR now instead of merging, right? Since this BMS Tutorial is now being used as the Equation Discovery Tutorial in ```autora```

2023-09-28 12:29 UTC, benwandrew commented
> @benwandrew we should close this PR now instead of merging, right? Since this BMS Tutorial is now being used as the Equation Discovery Tutorial in `autora`

i think that's right; we should probably close this now...

2023-09-28 12:40 UTC, closed without merging